### ISSUE TITLE
Can't open Latex compilation error log

### ISSUE THREAD

**Issue by Honpray** [thomasjo/atom-latex#226]
Windows 8 atom latex 0.36.0
I can compile and get a output of the correct part of the codes but I can't open the log to see what's going wrong.
But thanks for your efforts on this amazing package on atom~

**Comment by yitzchak** [comment]
Thanks for submitting the issue! This has been fixed in our master branch and will be in the next version. I'll close after we push out the next version and you confirm that it is fixed.

**Comment by yitzchak** [comment]
Can you upgrade to v0.36.1 and verify that this still exists?

**Comment by Honpray** [comment]
@yitzchak Solved! After upgrading to v0.36.1. Thanks a lot.
