### ISSUE TITLE
Bug when you compile an error

### ISSUE THREAD

**Issue by Rdbllx** [thomasjo/atom-latex#113]
Hello,
I noticed that when you want to construct a text file and it contains an error, after I emended it, I can't compile anymore. I have to close atom. Is it normal? 
Thanks in advance.

**Comment by thomasjo** [comment]
This is definitely not normal behavior. If you could provide us with a minimal example that reproduces the problem, that would be brilliant. In addition it'd be great if you could provide the following information
 1. What version of Atom are you running?
 2. What version of atom-latex are you using?
 3. Are you using TeX Live or MiKTeX?
 4. Which *Builder* are you using—`latexmk` or `texify`? If you haven't changed the builder setting, the default is `latexmk`.
 5. What operating system (including version) are you running?

**Comment by Rdbllx** [comment]
Ok, sorry for this lack.
So I work with atom 1.0.7 , the version 0.25.0 of atom-latex.
I use MikTeX and texify as Builder.
Finally I run under windows 7 64 bits.

**Comment by Rdbllx** [comment]
As example : 
the simpliest TeX document : 

\documentclass[a4paper, 12]{article}
\begin{document}
  Hello world
\end{document}

So I can build this document. But if I make a syntax mistake like for example I've forgotten the last bracket and I compile it. At the right bottom of atom I've got : LaTeX compilation error. 
This is normal but when I emend this document, I can't build it again. I've to restart atom.

**Comment by thomasjo** [comment]
Seems like this might be an issue with texify itself, and specifically how it determines whether a rebuild is necessary. I'll investigate if there are some command-line parameters I can use/tweak to change the current behavior.

**Comment by yitzchak** [comment]
I am closing this issue, because we are deprecating support for texify. Current functionality will be maintained during a phase out period, but no new functionality will be added. Please consider switching to latexmk as your builder. Please see [Using latexmk on MiKTeX](https://github.com/thomasjo/atom-latex/wiki/Using-latexmk-on-MiKTeX) for installation documentation.
