### ISSUE TITLE
LaTeX compilation error

### ISSUE THREAD

**Issue by phantomachine** [thomasjo/atom-latex#173]
The latest revision on Atom LaTeX package seems to have broken something. I get a "LateX compilation error" warning. Then I checked: No error log produced. Nothing was run. To be sure, I compiled them directly outside of Atom using latexmk and it all works fine.

**Comment by wupeifan** [comment]
Same here.  I use xelatex outside and it works fine.

**Comment by thomasjo** [comment]
Can both of you provide a minimal example that reliably reproduces the problem? Also I'll need information on your TeX distribution (TeX Live or MiKTeX).

**Comment by phantomachine** [comment]
Hello Thomas, I forgot to thank you for sharing such a nice module in Atom. I've been enjoying using it! 

The problem arises on my Atom editor running on Fedora Core 23, usinng either TexLive2014 or TeXLive2015. (I switched between both TeXLive distros to double check.)

Symptoms: 

- It was working fine until two days ago (approx.) when I updated atom-latex and pdf-view (from v.0.48 to 0.50). I thought it might be pdf-view, but even after I disabled it, running Ctrl+alt-b on a clean test LaTeX file/folder produces nothing except for the red "LaTeX compilation error" warning on Atom, with no log and no other files being typeset by latexmk in the back-end.

- Also, on my Dell laptop running Centos 7, I also have the latest revision of atom-latex but the older pdf-view (v. 0.48) which still seems to work fine for all my LaTeX files.

Below is my example LaTeX document which runs fine either via latexmk or directly via latex commands on the bash terminal:

`
\documentclass[11pt]{article}

\usepackage{xifthen}
\newboolean{answer}
\setboolean{answer}{true}

 \usepackage{tikz}
\usetikzlibrary{arrows,calc}
\tikzset{
	%Define standard arrow tip
	>=stealth',
	%Define style for different line styles
	help lines/.style={dashed, thick},
	axis/.style={<->},
	important line/.style={thick},
	connection/.style={thick, dotted},
}


\usepackage{amssymb}
\usepackage{amsmath}
\usepackage{hyperref}
\IfFileExists{url.sty}{\usepackage{url}}
                      {\newcommand{\url}{\texttt}}
\usepackage{fancyhdr}

\usepackage{graphicx}
\usepackage{epstopdf}

\usepackage{color,fancybox}


\setcounter{MaxMatrixCols}{10}

\setlength{\topmargin}{-1.0in}
\setlength{\textheight}{9.25in}
\setlength{\oddsidemargin}{0.0in}
\setlength{\evensidemargin}{0.0in}
\setlength{\textwidth}{6.5in}
\def\labelenumi{\arabic{enumi}.}
\def\theenumi{\arabic{enumi}}
\def\labelenumii{(\alph{enumii})}
\def\theenumii{\alph{enumii}}
\def\p@enumii{\theenumi.}
\def\labelenumiii{\arabic{enumiii}.}
\def\theenumiii{\arabic{enumiii}}
\def\p@enumiii{(\theenumi)(\theenumii)}
\def\labelenumiv{\arabic{enumiv}.}
\def\theenumiv{\arabic{enumiv}}
\def\p@enumiv{\p@enumiii.\theenumiii}
\pagestyle{plain}
\setcounter{secnumdepth}{0}
\parindent=2em

\pagestyle{fancy}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}
\lhead{}
\chead{}
\rhead{}
\lfoot{}
\cfoot{}
\rfoot{Page \ \thepage}
\footskip = 40pt
\headsep = 30pt

\newtheorem{thm}{Theorem}
\newtheorem{defn}{Definition}
\newtheorem{prop}{Proposition}
\newtheorem{lem}{Lemma}
\newtheorem{cor}{Corollary}
\newtheorem{ass}{Assumption}
\newtheorem{sol}{Solution}

\def\R{\mathbb{R}}

\def\N{\mathbb{N}}

\def\beq{\begin{equation}}
\def\eeq{\end{equation}}

\newcommand{\bol}{\begin{enumerate}}
\newcommand{\eol}{\end{enumerate}}
\newcommand{\bul}{\begin{itemize}}
\newcommand{\eul}{\end{itemize}}
\newcommand{\li}{\item}

% Answer box:
\newenvironment{abox}[2][\textbf{Answer Key $\triangleright$}]{\shadowbox{\begin{minipage}[b]{0.9\textwidth} #1 {\color{blue}#2} \ $\hfill \rule{0.5em}{0.5em}\blacktriangleleft$ \end{minipage}}}{}


\begin{document}

%% DRAFT WARNING
%\thisfancyput(4cm,-19cm){\Huge\bfseries\textcolor{red}{\rotatebox{45}{DO NOT DISTRIBUTE}}}

\begin{center}
\bigskip

\bigskip

\textbf{ECON1102\quad  \today}

\textbf{Problem Set 1: Introduction: What is Macro and How?}
\end{center}

\end{document}
`

**Comment by thomasjo** [comment]
@phantomachine Hmm, this is really odd. What version(s) of Atom are you using on the two machines?

**Comment by phantomachine** [comment]
Hi Thomas,

* Desktop with Fedora 23: atom 1.0.16

* Laptop with Centos 7: atom 1.4.0

I guess I should update the version on the desktop?

**Comment by thomasjo** [comment]
@phantomachine Really glad you resolved your problem! :smile:

**Comment by wupeifan** [comment]
I updated my atom version to 1.6.0 and now it works. So I guess the issue is exactly like @phantomachine's.

**Comment by thomasjo** [comment]
@wupeifan Thanks for the update! Glad it's working again :smiley:
